//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KelionesIMarsa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Naudotoja
    {
        [Required(ErrorMessage = "Vardas yra privalomas")]
        public string Vardas { get; set; }

        [Required(ErrorMessage = "Pavarde yra privaloma")]
        public string Pavarde { get; set; }

        [DisplayName("Elektroninis paštas")]
        public string ElPastas { get; set; }

        [DisplayName("Slaptažodis")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Slaptažodis yra privalomas")]
        public string Slaptazodis { get; set; }

        public int id_Naudotojas { get; set; }

        [DisplayName("Ar adminas")]
        public bool ArAdminas { get; set; }

    }
}
