//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KelionesIMarsa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patiekala
    {
        public string Pavadinimas { get; set; }
        public int Kalorijos { get; set; }
        public string Tipas { get; set; }
        public int id_Patiekalas { get; set; }
    }
}
